framework:
    default_locale: 'fr'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - 'ja'
            - 'fr'
            - 'ru'
            - 'en'